/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AProposRouteImport } from './routes/a-propos'
import { Route as BoutiqueRouteImport } from './routes/boutique'
import { Route as CategoriesRouteImport } from './routes/categories'
import { Route as CommanderRouteImport } from './routes/commander'
import { Route as ConditionsRouteImport } from './routes/conditions'
import { Route as ConfidentialiteRouteImport } from './routes/confidentialite'
import { Route as ConnexionRouteImport } from './routes/connexion'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as InscriptionRouteImport } from './routes/inscription'
import { Route as MotDePasseOublieRouteImport } from './routes/mot-de-passe-oublie'
import { Route as PanierRouteImport } from './routes/panier'
import { Route as ReinitialiserMotDePasseRouteImport } from './routes/reinitialiser-mot-de-passe'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminCommandesRouteImport } from './routes/admin.commandes'
import { Route as AdminParametresRouteImport } from './routes/admin.parametres'
import { Route as AdminPromotionsRouteImport } from './routes/admin.promotions'
import { Route as AdminStatistiquesRouteImport } from './routes/admin.statistiques'
import { Route as AdminUtilisateursRouteImport } from './routes/admin.utilisateurs'
import { Route as CompteIndexRouteImport } from './routes/compte.index'
import { Route as CompteAdressesRouteImport } from './routes/compte.adresses'
import { Route as CompteFavorisRouteImport } from './routes/compte.favoris'
import { Route as CompteProfilRouteImport } from './routes/compte.profil'
import { Route as ProduitSlugRouteImport } from './routes/produit.$slug'
import { Route as AdminProduitsIndexRouteImport } from './routes/admin.produits.index'
import { Route as AdminProduitsIdRouteImport } from './routes/admin.produits.$id'
import { Route as AdminProduitsNouveauRouteImport } from './routes/admin.produits.nouveau'
import { Route as CompteCommandesIndexRouteImport } from './routes/compte.commandes.index'
import { Route as CompteCommandesIdRouteImport } from './routes/compte.commandes.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AProposRoute = AProposRouteImport.update({
  id: '/a-propos',
  path: '/a-propos',
  getParentRoute: () => rootRouteImport,
} as any)
const BoutiqueRoute = BoutiqueRouteImport.update({
  id: '/boutique',
  path: '/boutique',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesRoute = CategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const CommanderRoute = CommanderRouteImport.update({
  id: '/commander',
  path: '/commander',
  getParentRoute: () => rootRouteImport,
} as any)
const ConditionsRoute = ConditionsRouteImport.update({
  id: '/conditions',
  path: '/conditions',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfidentialiteRoute = ConfidentialiteRouteImport.update({
  id: '/confidentialite',
  path: '/confidentialite',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnexionRoute = ConnexionRouteImport.update({
  id: '/connexion',
  path: '/connexion',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const InscriptionRoute = InscriptionRouteImport.update({
  id: '/inscription',
  path: '/inscription',
  getParentRoute: () => rootRouteImport,
} as any)
const MotDePasseOublieRoute = MotDePasseOublieRouteImport.update({
  id: '/mot-de-passe-oublie',
  path: '/mot-de-passe-oublie',
  getParentRoute: () => rootRouteImport,
} as any)
const PanierRoute = PanierRouteImport.update({
  id: '/panier',
  path: '/panier',
  getParentRoute: () => rootRouteImport,
} as any)
const ReinitialiserMotDePasseRoute = ReinitialiserMotDePasseRouteImport.update({
  id: '/reinitialiser-mot-de-passe',
  path: '/reinitialiser-mot-de-passe',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCommandesRoute = AdminCommandesRouteImport.update({
  id: '/admin/commandes',
  path: '/admin/commandes',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminParametresRoute = AdminParametresRouteImport.update({
  id: '/admin/parametres',
  path: '/admin/parametres',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPromotionsRoute = AdminPromotionsRouteImport.update({
  id: '/admin/promotions',
  path: '/admin/promotions',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminStatistiquesRoute = AdminStatistiquesRouteImport.update({
  id: '/admin/statistiques',
  path: '/admin/statistiques',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUtilisateursRoute = AdminUtilisateursRouteImport.update({
  id: '/admin/utilisateurs',
  path: '/admin/utilisateurs',
  getParentRoute: () => rootRouteImport,
} as any)
const CompteIndexRoute = CompteIndexRouteImport.update({
  id: '/compte/',
  path: '/compte/',
  getParentRoute: () => rootRouteImport,
} as any)
const CompteAdressesRoute = CompteAdressesRouteImport.update({
  id: '/compte/adresses',
  path: '/compte/adresses',
  getParentRoute: () => rootRouteImport,
} as any)
const CompteFavorisRoute = CompteFavorisRouteImport.update({
  id: '/compte/favoris',
  path: '/compte/favoris',
  getParentRoute: () => rootRouteImport,
} as any)
const CompteProfilRoute = CompteProfilRouteImport.update({
  id: '/compte/profil',
  path: '/compte/profil',
  getParentRoute: () => rootRouteImport,
} as any)
const ProduitSlugRoute = ProduitSlugRouteImport.update({
  id: '/produit/$slug',
  path: '/produit/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProduitsIndexRoute = AdminProduitsIndexRouteImport.update({
  id: '/admin/produits/',
  path: '/admin/produits/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProduitsIdRoute = AdminProduitsIdRouteImport.update({
  id: '/admin/produits/$id',
  path: '/admin/produits/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProduitsNouveauRoute = AdminProduitsNouveauRouteImport.update({
  id: '/admin/produits/nouveau',
  path: '/admin/produits/nouveau',
  getParentRoute: () => rootRouteImport,
} as any)
const CompteCommandesIndexRoute = CompteCommandesIndexRouteImport.update({
  id: '/compte/commandes/',
  path: '/compte/commandes/',
  getParentRoute: () => rootRouteImport,
} as any)
const CompteCommandesIdRoute = CompteCommandesIdRouteImport.update({
  id: '/compte/commandes/$id',
  path: '/compte/commandes/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/boutique': typeof BoutiqueRoute
  '/categories': typeof CategoriesRoute
  '/commander': typeof CommanderRoute
  '/conditions': typeof ConditionsRoute
  '/confidentialite': typeof ConfidentialiteRoute
  '/connexion': typeof ConnexionRoute
  '/contact': typeof ContactRoute
  '/inscription': typeof InscriptionRoute
  '/mot-de-passe-oublie': typeof MotDePasseOublieRoute
  '/panier': typeof PanierRoute
  '/reinitialiser-mot-de-passe': typeof ReinitialiserMotDePasseRoute
  '/admin/commandes': typeof AdminCommandesRoute
  '/admin/parametres': typeof AdminParametresRoute
  '/admin/promotions': typeof AdminPromotionsRoute
  '/admin/statistiques': typeof AdminStatistiquesRoute
  '/admin/utilisateurs': typeof AdminUtilisateursRoute
  '/compte/adresses': typeof CompteAdressesRoute
  '/compte/favoris': typeof CompteFavorisRoute
  '/compte/profil': typeof CompteProfilRoute
  '/produit/$slug': typeof ProduitSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/compte/': typeof CompteIndexRoute
  '/admin/produits/$id': typeof AdminProduitsIdRoute
  '/admin/produits/nouveau': typeof AdminProduitsNouveauRoute
  '/compte/commandes/$id': typeof CompteCommandesIdRoute
  '/admin/produits/': typeof AdminProduitsIndexRoute
  '/compte/commandes/': typeof CompteCommandesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/boutique': typeof BoutiqueRoute
  '/categories': typeof CategoriesRoute
  '/commander': typeof CommanderRoute
  '/conditions': typeof ConditionsRoute
  '/confidentialite': typeof ConfidentialiteRoute
  '/connexion': typeof ConnexionRoute
  '/contact': typeof ContactRoute
  '/inscription': typeof InscriptionRoute
  '/mot-de-passe-oublie': typeof MotDePasseOublieRoute
  '/panier': typeof PanierRoute
  '/reinitialiser-mot-de-passe': typeof ReinitialiserMotDePasseRoute
  '/admin/commandes': typeof AdminCommandesRoute
  '/admin/parametres': typeof AdminParametresRoute
  '/admin/promotions': typeof AdminPromotionsRoute
  '/admin/statistiques': typeof AdminStatistiquesRoute
  '/admin/utilisateurs': typeof AdminUtilisateursRoute
  '/compte/adresses': typeof CompteAdressesRoute
  '/compte/favoris': typeof CompteFavorisRoute
  '/compte/profil': typeof CompteProfilRoute
  '/produit/$slug': typeof ProduitSlugRoute
  '/admin': typeof AdminIndexRoute
  '/compte': typeof CompteIndexRoute
  '/admin/produits/$id': typeof AdminProduitsIdRoute
  '/admin/produits/nouveau': typeof AdminProduitsNouveauRoute
  '/compte/commandes/$id': typeof CompteCommandesIdRoute
  '/admin/produits': typeof AdminProduitsIndexRoute
  '/compte/commandes': typeof CompteCommandesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/boutique': typeof BoutiqueRoute
  '/categories': typeof CategoriesRoute
  '/commander': typeof CommanderRoute
  '/conditions': typeof ConditionsRoute
  '/confidentialite': typeof ConfidentialiteRoute
  '/connexion': typeof ConnexionRoute
  '/contact': typeof ContactRoute
  '/inscription': typeof InscriptionRoute
  '/mot-de-passe-oublie': typeof MotDePasseOublieRoute
  '/panier': typeof PanierRoute
  '/reinitialiser-mot-de-passe': typeof ReinitialiserMotDePasseRoute
  '/admin/commandes': typeof AdminCommandesRoute
  '/admin/parametres': typeof AdminParametresRoute
  '/admin/promotions': typeof AdminPromotionsRoute
  '/admin/statistiques': typeof AdminStatistiquesRoute
  '/admin/utilisateurs': typeof AdminUtilisateursRoute
  '/compte/adresses': typeof CompteAdressesRoute
  '/compte/favoris': typeof CompteFavorisRoute
  '/compte/profil': typeof CompteProfilRoute
  '/produit/$slug': typeof ProduitSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/compte/': typeof CompteIndexRoute
  '/admin/produits/$id': typeof AdminProduitsIdRoute
  '/admin/produits/nouveau': typeof AdminProduitsNouveauRoute
  '/compte/commandes/$id': typeof CompteCommandesIdRoute
  '/admin/produits/': typeof AdminProduitsIndexRoute
  '/compte/commandes/': typeof CompteCommandesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/a-propos'
    | '/boutique'
    | '/categories'
    | '/commander'
    | '/conditions'
    | '/confidentialite'
    | '/connexion'
    | '/contact'
    | '/inscription'
    | '/mot-de-passe-oublie'
    | '/panier'
    | '/reinitialiser-mot-de-passe'
    | '/admin/commandes'
    | '/admin/parametres'
    | '/admin/promotions'
    | '/admin/statistiques'
    | '/admin/utilisateurs'
    | '/compte/adresses'
    | '/compte/favoris'
    | '/compte/profil'
    | '/produit/$slug'
    | '/admin/'
    | '/compte/'
    | '/admin/produits/$id'
    | '/admin/produits/nouveau'
    | '/compte/commandes/$id'
    | '/admin/produits/'
    | '/compte/commandes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/a-propos'
    | '/boutique'
    | '/categories'
    | '/commander'
    | '/conditions'
    | '/confidentialite'
    | '/connexion'
    | '/contact'
    | '/inscription'
    | '/mot-de-passe-oublie'
    | '/panier'
    | '/reinitialiser-mot-de-passe'
    | '/admin/commandes'
    | '/admin/parametres'
    | '/admin/promotions'
    | '/admin/statistiques'
    | '/admin/utilisateurs'
    | '/compte/adresses'
    | '/compte/favoris'
    | '/compte/profil'
    | '/produit/$slug'
    | '/admin'
    | '/compte'
    | '/admin/produits/$id'
    | '/admin/produits/nouveau'
    | '/compte/commandes/$id'
    | '/admin/produits'
    | '/compte/commandes'
  id:
    | '__root__'
    | '/'
    | '/a-propos'
    | '/boutique'
    | '/categories'
    | '/commander'
    | '/conditions'
    | '/confidentialite'
    | '/connexion'
    | '/contact'
    | '/inscription'
    | '/mot-de-passe-oublie'
    | '/panier'
    | '/reinitialiser-mot-de-passe'
    | '/admin/commandes'
    | '/admin/parametres'
    | '/admin/promotions'
    | '/admin/statistiques'
    | '/admin/utilisateurs'
    | '/compte/adresses'
    | '/compte/favoris'
    | '/compte/profil'
    | '/produit/$slug'
    | '/admin/'
    | '/compte/'
    | '/admin/produits/$id'
    | '/admin/produits/nouveau'
    | '/compte/commandes/$id'
    | '/admin/produits/'
    | '/compte/commandes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AProposRoute: typeof AProposRoute
  BoutiqueRoute: typeof BoutiqueRoute
  CategoriesRoute: typeof CategoriesRoute
  CommanderRoute: typeof CommanderRoute
  ConditionsRoute: typeof ConditionsRoute
  ConfidentialiteRoute: typeof ConfidentialiteRoute
  ConnexionRoute: typeof ConnexionRoute
  ContactRoute: typeof ContactRoute
  InscriptionRoute: typeof InscriptionRoute
  MotDePasseOublieRoute: typeof MotDePasseOublieRoute
  PanierRoute: typeof PanierRoute
  ReinitialiserMotDePasseRoute: typeof ReinitialiserMotDePasseRoute
  AdminCommandesRoute: typeof AdminCommandesRoute
  AdminParametresRoute: typeof AdminParametresRoute
  AdminPromotionsRoute: typeof AdminPromotionsRoute
  AdminStatistiquesRoute: typeof AdminStatistiquesRoute
  AdminUtilisateursRoute: typeof AdminUtilisateursRoute
  CompteAdressesRoute: typeof CompteAdressesRoute
  CompteFavorisRoute: typeof CompteFavorisRoute
  CompteProfilRoute: typeof CompteProfilRoute
  ProduitSlugRoute: typeof ProduitSlugRoute
  AdminIndexRoute: typeof AdminIndexRoute
  CompteIndexRoute: typeof CompteIndexRoute
  AdminProduitsIdRoute: typeof AdminProduitsIdRoute
  AdminProduitsNouveauRoute: typeof AdminProduitsNouveauRoute
  CompteCommandesIdRoute: typeof CompteCommandesIdRoute
  AdminProduitsIndexRoute: typeof AdminProduitsIndexRoute
  CompteCommandesIndexRoute: typeof CompteCommandesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/a-propos': {
      id: '/a-propos'
      path: '/a-propos'
      fullPath: '/a-propos'
      preLoaderRoute: typeof AProposRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/boutique': {
      id: '/boutique'
      path: '/boutique'
      fullPath: '/boutique'
      preLoaderRoute: typeof BoutiqueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories': {
      id: '/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof CategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/commander': {
      id: '/commander'
      path: '/commander'
      fullPath: '/commander'
      preLoaderRoute: typeof CommanderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conditions': {
      id: '/conditions'
      path: '/conditions'
      fullPath: '/conditions'
      preLoaderRoute: typeof ConditionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confidentialite': {
      id: '/confidentialite'
      path: '/confidentialite'
      fullPath: '/confidentialite'
      preLoaderRoute: typeof ConfidentialiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connexion': {
      id: '/connexion'
      path: '/connexion'
      fullPath: '/connexion'
      preLoaderRoute: typeof ConnexionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inscription': {
      id: '/inscription'
      path: '/inscription'
      fullPath: '/inscription'
      preLoaderRoute: typeof InscriptionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mot-de-passe-oublie': {
      id: '/mot-de-passe-oublie'
      path: '/mot-de-passe-oublie'
      fullPath: '/mot-de-passe-oublie'
      preLoaderRoute: typeof MotDePasseOublieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/panier': {
      id: '/panier'
      path: '/panier'
      fullPath: '/panier'
      preLoaderRoute: typeof PanierRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reinitialiser-mot-de-passe': {
      id: '/reinitialiser-mot-de-passe'
      path: '/reinitialiser-mot-de-passe'
      fullPath: '/reinitialiser-mot-de-passe'
      preLoaderRoute: typeof ReinitialiserMotDePasseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/commandes': {
      id: '/admin/commandes'
      path: '/admin/commandes'
      fullPath: '/admin/commandes'
      preLoaderRoute: typeof AdminCommandesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/parametres': {
      id: '/admin/parametres'
      path: '/admin/parametres'
      fullPath: '/admin/parametres'
      preLoaderRoute: typeof AdminParametresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/promotions': {
      id: '/admin/promotions'
      path: '/admin/promotions'
      fullPath: '/admin/promotions'
      preLoaderRoute: typeof AdminPromotionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/statistiques': {
      id: '/admin/statistiques'
      path: '/admin/statistiques'
      fullPath: '/admin/statistiques'
      preLoaderRoute: typeof AdminStatistiquesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/utilisateurs': {
      id: '/admin/utilisateurs'
      path: '/admin/utilisateurs'
      fullPath: '/admin/utilisateurs'
      preLoaderRoute: typeof AdminUtilisateursRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compte/': {
      id: '/compte/'
      path: '/compte'
      fullPath: '/compte/'
      preLoaderRoute: typeof CompteIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compte/adresses': {
      id: '/compte/adresses'
      path: '/compte/adresses'
      fullPath: '/compte/adresses'
      preLoaderRoute: typeof CompteAdressesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compte/favoris': {
      id: '/compte/favoris'
      path: '/compte/favoris'
      fullPath: '/compte/favoris'
      preLoaderRoute: typeof CompteFavorisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compte/profil': {
      id: '/compte/profil'
      path: '/compte/profil'
      fullPath: '/compte/profil'
      preLoaderRoute: typeof CompteProfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produit/$slug': {
      id: '/produit/$slug'
      path: '/produit/$slug'
      fullPath: '/produit/$slug'
      preLoaderRoute: typeof ProduitSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/produits/': {
      id: '/admin/produits/'
      path: '/admin/produits'
      fullPath: '/admin/produits/'
      preLoaderRoute: typeof AdminProduitsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/produits/$id': {
      id: '/admin/produits/$id'
      path: '/admin/produits/$id'
      fullPath: '/admin/produits/$id'
      preLoaderRoute: typeof AdminProduitsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/produits/nouveau': {
      id: '/admin/produits/nouveau'
      path: '/admin/produits/nouveau'
      fullPath: '/admin/produits/nouveau'
      preLoaderRoute: typeof AdminProduitsNouveauRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compte/commandes/': {
      id: '/compte/commandes/'
      path: '/compte/commandes'
      fullPath: '/compte/commandes/'
      preLoaderRoute: typeof CompteCommandesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compte/commandes/$id': {
      id: '/compte/commandes/$id'
      path: '/compte/commandes/$id'
      fullPath: '/compte/commandes/$id'
      preLoaderRoute: typeof CompteCommandesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AProposRoute: AProposRoute,
  BoutiqueRoute: BoutiqueRoute,
  CategoriesRoute: CategoriesRoute,
  CommanderRoute: CommanderRoute,
  ConditionsRoute: ConditionsRoute,
  ConfidentialiteRoute: ConfidentialiteRoute,
  ConnexionRoute: ConnexionRoute,
  ContactRoute: ContactRoute,
  InscriptionRoute: InscriptionRoute,
  MotDePasseOublieRoute: MotDePasseOublieRoute,
  PanierRoute: PanierRoute,
  ReinitialiserMotDePasseRoute: ReinitialiserMotDePasseRoute,
  AdminCommandesRoute: AdminCommandesRoute,
  AdminParametresRoute: AdminParametresRoute,
  AdminPromotionsRoute: AdminPromotionsRoute,
  AdminStatistiquesRoute: AdminStatistiquesRoute,
  AdminUtilisateursRoute: AdminUtilisateursRoute,
  CompteAdressesRoute: CompteAdressesRoute,
  CompteFavorisRoute: CompteFavorisRoute,
  CompteProfilRoute: CompteProfilRoute,
  ProduitSlugRoute: ProduitSlugRoute,
  AdminIndexRoute: AdminIndexRoute,
  CompteIndexRoute: CompteIndexRoute,
  AdminProduitsIdRoute: AdminProduitsIdRoute,
  AdminProduitsNouveauRoute: AdminProduitsNouveauRoute,
  CompteCommandesIdRoute: CompteCommandesIdRoute,
  AdminProduitsIndexRoute: AdminProduitsIndexRoute,
  CompteCommandesIndexRoute: CompteCommandesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
